### ISSUE TITLE
All info in the the toolbar is invisible

### ISSUE THREAD

**Issue by keelangibb** [KajSzy/next-cache-toolbar#2]
This seems pretty useful but I can't see any of the info displayed like you show in the screenshot. I think I had two blank entries. I would like to know if I'm doing something wrong. Working on a Mac with pnpm.

**Comment by KajSzy** [comment]
Did you open a panel? After adding code snippet there should be button with "{}"
If there are no valid entries toolbar should be shown empty. 
I hope to release soon some fixes to parsing files and add proper error handling to help identify issues more precisely.

**Comment by keelangibb** [comment]
I think I figured it out. When dark mode is enabled on my website the text is invisible on the toolbar. Im using the shadcn/ui example of a dark mode switcher. Im assuming it has to do with the text color not getting swapped to the opposite of the background color and that's why it's invisible on dark mode. 

Light Mode
<img width="1496" alt="Screenshot 2024-03-05 at 2 23 40 PM" src="https://github.com/KajSzy/next-cache-toolbar/assets/59493312/02ed015a-e099-466c-bed4-859de1b71712">

Dark Mode...
<img width="1496" alt="Screenshot 2024-03-05 at 2 24 29 PM" src="https://github.com/KajSzy/next-cache-toolbar/assets/59493312/b9962134-f8ce-4f43-b68a-515d4888128d">

**Comment by keelangibb** [comment]
Also those api calls are no longer in my codebase anymore and they are still being displayed in the toolbar.

**Comment by KajSzy** [comment]
> I think I figured it out. When dark mode is enabled on my website the text is invisible on the toolbar. Im using the shadcn/ui example of a dark mode switcher. Im assuming it has to do with the text color not getting swapped to the opposite of the background color and that's why it's invisible on dark mode.
> 
> Light Mode <img alt="Screenshot 2024-03-05 at 2 23 40 PM" width="1496" src="https://private-user-images.githubusercontent.com/59493312/310268673-02ed015a-e099-466c-bed4-859de1b71712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Nzg2ODUsIm5iZiI6MTcwOTY3ODM4NSwicGF0aCI6Ii81OTQ5MzMxMi8zMTAyNjg2NzMtMDJlZDAxNWEtZTA5OS00NjZjLWJlZDQtODU5ZGUxYjcxNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIyMzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZDJlNjU2NjUxMDcyZGMzY2NmNmMzMGRmYzAzNTc4ODgzOTExNDQ2MjNhY2M0OGEwMjJjNzBlOTlmZmFjZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8jDTBk5GspGK2w_b8LllQn97KFuVSNEV1YXKbwMAfw">
> 
> Dark Mode... <img alt="Screenshot 2024-03-05 at 2 24 29 PM" width="1496" src="https://private-user-images.githubusercontent.com/59493312/310268917-b9962134-f8ce-4f43-b68a-515d4888128d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Nzg2ODUsIm5iZiI6MTcwOTY3ODM4NSwicGF0aCI6Ii81OTQ5MzMxMi8zMTAyNjg5MTctYjk5NjIxMzQtZjhjZS00ZjQzLWI2OGEtNTE1ZDQ4ODgxMjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIyMzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNjczNmIwYjAzYTVjMmIwODJmNDYwYTYwMjk0NGViY2M4YmZmNGFiN2M5YjY0OGFlZDQzMmEwNzNlOThiY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VdmBWpRmDp1T1Z1S82J7MbX2aDW0HEvgAiFiLLSxQL0">

I've just released an update to fix issues of conflicting styles. Now it should be visible 


> Also those api calls are no longer in my codebase anymore and they are still being displayed in the toolbar.

Sadly, those are calls that are currently in `.next/cache/fetch-cache` directory which isn't cleaned up unless `next build` is run.
Either ignore them or remove whole `.next` directory

**Comment by KajSzy** [comment]
Seems to be fixed now
