### ISSUE TITLE
runtime error: node:fs/promises

### ISSUE THREAD

**Issue by Diabl0570** [KajSzy/next-cache-toolbar#3]
Some info: 
Im running in a Turborepo,
nextjs 14.1
nodejs 20.5.1
I have this error in two projects (both part of the same monorepo)

I tried deleting .next directory and running pnpm dev again, but same result.

```
node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

**Comment by ashinpaugh** [comment]
Really looks like the author is trying to fight an uphill battle trying to support Vercel's recommended solution since the caching strategy imports as "unstable_cache," which might be fine but what's more telling is Vercel's own redis cache handler's "key features" documentation links to the void

https://github.com/vercel/next.js/tree/canary/examples/cache-handler-redis

**Comment by KajSzy** [comment]
> Really looks like the author is trying to fight an uphill battle trying to support Vercel's recommended solution since the caching strategy imports as "unstable_cache," which might be fine but what's more telling is Vercel's own redis cache handler's "key features" documentation links to the void
> 
> https://github.com/vercel/next.js/tree/canary/examples/cache-handler-redis

Linked repo uses redis as cache layer which is well tested and well documented solution.
This repo tries to help people understand and use built-in cache mechanism which might be good enough to use in most cases.
Sadly Vercel when releasing app router did not communicate clear enough how app router cache works.
Months after release they did provide well written docs that to me should be more promoted ([link here](https://nextjs.org/docs/app/building-your-application/caching))

To be clear, this toolbar will get only cache from [data cache](https://nextjs.org/docs/app/building-your-application/caching#data-cache) which might not be the most irritating one.

The ideal solution would be that Vercel from day one would provide such toolbar that could help investigate which cache client hits. 
This [tweet ](https://x.com/rauchg/status/1757402186060083272) indicates that they are working on something like this
