### ISSUE TITLE
CSS gets applied for the whole app

### ISSUE THREAD

**Issue by ioulian** [KajSzy/next-cache-toolbar#5]
When using the toolbar, the css that gets imported is not scoped to the library, so the whole site is being changed.

Possible fix is to scope the css inside a specific className and wrap the component with this className.

Great idea and very useful package, but not usable right now

**Comment by KajSzy** [comment]
Should be fixed in `0.2.1`

**Comment by ioulian** [comment]
Yes, great, it works! Thanks
